import{test}from'node:test';import assert from'node:assert/strict';import{achievements,levelColor,levelForRating,progressEvents,ratingFromHistory}from'../src/gamification.ts';import type{WorkoutSession}from'../src/data.ts';
const session=(id:string,mode:WorkoutSession['mode'],date:string,reps=10,extra:Partial<WorkoutSession>={}):WorkoutSession=>({id,mode,date,reps,seconds:60,goal:5,...extra});
test('gamification journal uses deterministic unique event ids and daily caps',()=>{const history=[session('a','free','2026-09-01T10:00:00Z'),session('b','free','2026-09-01T11:00:00Z'),session('c','free','2026-09-01T12:00:00Z'),session('d','pvp','2026-09-01T13:00:00Z',12,{pvpResult:'win'})];const events=progressEvents(history);assert.equal(events.filter(e=>e.type==='free').length,2);assert.equal(events.filter(e=>e.type==='pvp_finish').length,1);assert.equal(new Set(events.map(e=>e.id)).size,events.length)});
test('three main workouts award the weekly bonus',()=>{const events=progressEvents([session('a','program','2026-09-01T10:00:00Z'),session('b','program','2026-09-03T10:00:00Z'),session('c','program','2026-09-05T10:00:00Z')]);assert.equal(events.filter(e=>e.type==='weekly_goal').length,1)});
test('PWR starts at LVL 3 and uses branded level thresholds',()=>{assert.equal(levelForRating(599).level,1);assert.equal(levelForRating(600).level,2);assert.equal(levelForRating(900).level,3);assert.equal(levelForRating(1000).level,3);assert.equal(levelForRating(2000).level,10)});
test('PWR levels use the competitive green to red color scale',()=>{assert.equal(levelColor(2),'#1CE400');assert.equal(levelColor(4),'#FFC800');assert.equal(levelColor(8),'#FF6309');assert.equal(levelColor(10),'#FE1F00')});
test('only PvP outcomes change PWR',()=>{const win=session('b','pvp','2026-09-02T10:00:00Z',12,{pvpResult:'win'}),history=[session('a','free','2026-09-01T10:00:00Z'),win,session('c','pvp','2026-09-03T10:00:00Z',9,{pvpResult:'loss'}),session('d','pvp','2026-09-04T10:00:00Z',10,{pvpResult:'draw'})];assert.equal(ratingFromHistory(history).rating,1000);assert.equal(ratingFromHistory([win]).rating,1025)});
test('saved PWR checkpoints keep rating stable',()=>{const history=[session('a','pvp','2026-09-01T10:00:00Z',12,{pvpResult:'win',ratingDelta:25,ratingAfter:1300}),session('b','pvp','2026-09-02T10:00:00Z',8,{pvpResult:'loss',ratingDelta:-25,ratingAfter:1275})];assert.equal(ratingFromHistory(history).rating,1275);assert.equal(ratingFromHistory(history).level,5)});
test('extended collection unlocks cumulative, consistency and match milestones',()=>{const history=Array.from({length:25},(_,index)=>{const mode:WorkoutSession['mode']=index<10?'program':index<20?'pvp':'free';return session(`m${index}`,mode,`2026-09-${String(index+1).padStart(2,'0')}T10:00:00Z`,index<10?50:index<20?30:40,mode==='pvp'?{pvpResult:'win'}:{})});const items=achievements(history,null),byId=new Map(items.map(item=>[item.id,item]));for(const id of['regular','discipline','century','thousand','ten-wins','speed'])assert.ok(byId.get(id)?.unlockedAt,`${id} should be unlocked`);assert.equal(items.length,12)});
