import React,{useState}from'react';
import{StyleSheet,Text,View}from'react-native';
import{useApp}from'../state/AppContext';
import type{SessionKind}from'../data';
import{Card,colors,Screen,Segmented}from'../ui';
type Filter='all'|SessionKind;
const names:Record<SessionKind,string>={program:'Основная',light:'Лёгкая',free:'Свободная',pvp:'Матч'};
const pvpColor=(result?:'win'|'loss'|'draw')=>result==='win'?colors.win:result==='loss'?colors.loss:result==='draw'?colors.draw:undefined;
export default function HistoryScreen(){const{history}=useApp(),[filter,setFilter]=useState<Filter>('all');const items=filter==='all'?history:history.filter(item=>item.mode===filter);return <Screen><Segmented value={filter} onChange={setFilter} options={[{value:'all',label:'Все'},{value:'program',label:'Программа'},{value:'free',label:'Свободные'},{value:'pvp',label:'Матчи'}]}/>{items.length===0?<View style={s.empty}><Text style={s.emptyTitle}>Здесь пока пусто</Text><Text style={s.emptyCopy}>Подходы этого типа появятся после сохранения.</Text></View>:<Card style={s.list}>{items.map((item,i)=>{const outcomeColor=item.mode==='pvp'?pvpColor(item.pvpResult):undefined;return <View key={item.id} style={[s.row,i>0&&s.line]}><View><Text style={s.title}>{names[item.mode]}{item.mode==='pvp'&&item.opponentNickname?` · ${item.opponentNickname}`:''}</Text><Text style={s.date}>{new Date(item.date).toLocaleString('ru-RU',{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})}</Text></View><View style={s.result}><Text style={[s.reps,outcomeColor&&{color:outcomeColor}]}>{item.reps}</Text><Text style={[s.time,outcomeColor&&{color:outcomeColor,fontWeight:'700'}]}>{item.mode==='pvp'?(item.pvpResult==='win'?'победа':item.pvpResult==='loss'?'поражение':'ничья'):`${Math.floor(item.seconds/60).toString().padStart(2,'0')}:${(item.seconds%60).toString().padStart(2,'0')}`}</Text></View></View>})}</Card>}</Screen>}
const s=StyleSheet.create({list:{paddingVertical:2},row:{minHeight:78,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},line:{borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:colors.line},title:{fontSize:16,fontWeight:'600'},date:{fontSize:12,color:colors.secondary,marginTop:4},result:{alignItems:'flex-end'},reps:{fontSize:28,fontWeight:'700'},time:{fontSize:11,color:colors.secondary},empty:{paddingTop:160,alignItems:'center'},emptyTitle:{fontSize:22,fontWeight:'700'},emptyCopy:{fontSize:14,color:colors.secondary,marginTop:7}});
