import React,{useCallback,useEffect,useRef,useState}from'react';
import{Animated,Platform,Pressable,Share,StyleSheet,Text,View}from'react-native';
import{router,useLocalSearchParams}from'expo-router';
import{Camera}from'expo-camera';import{StatusBar}from'expo-status-bar';import*as Haptics from'expo-haptics';
import{useSafeAreaInsets}from'react-native-safe-area-context';import{useKeepAwake}from'expo-keep-awake';
import CameraFeed,{type CameraEvent}from'../../CameraFeed';import{AutomaticCounter}from'../../automatic';import{useRepConfirmationSound}from'../../audio';import{broadcastScore,invokePvp,removeMatchChannel,subscribeToMatch,type PvpMatch}from'../../supabase';import{useApp}from'../../state/AppContext';import{colors,PrimaryButton}from'../../ui';
type Phase='waiting'|'countdown'|'active'|'result';const clock=(n:number)=>`00:${Math.max(0,n).toString().padStart(2,'0')}`;function Awake(){useKeepAwake();return null}
export default function PvpMatchScreen(){const p=useLocalSearchParams<{matchId?:string;demo?:string;nickname?:string;opponent?:string;code?:string}>(),demo=p.demo==='1',insets=useSafeAreaInsets(),{recordSession,profile}=useApp();
 const playRepSound=useRepConfirmationSound();
 const[phase,setPhase]=useState<Phase>('waiting'),[camera,setCamera]=useState(false),[hint,setHint]=useState('Покажи себя и стопы'),[score,setScore]=useState(0),[opponentScore,setOpponentScore]=useState(0),[opponentName,setOpponentName]=useState(p.opponent??'Соперник'),[remaining,setRemaining]=useState(60),[startAt,setStartAt]=useState(0),[error,setError]=useState(''),[saving,setSaving]=useState(false),[friendAdded,setFriendAdded]=useState(false),[pulse]=useState(()=>new Animated.Value(1));const engine=useRef(new AutomaticCounter()),stable=useRef(0),seq=useRef(0),channel=useRef<ReturnType<typeof subscribeToMatch>>(null);
 useEffect(()=>{void(async()=>{if(Platform.OS!=='web'){const permission=await Camera.requestCameraPermissionsAsync();if(!permission.granted){setError('Разреши камеру в настройках.');return}}setCamera(true)})();if(p.matchId){channel.current=subscribeToMatch(p.matchId,(event,payload)=>{if(event==='score'&&payload?.score>=0)setOpponentScore(payload.score);const value=event==='match'?payload:null;if((event==='start'&&payload?.startAt)||value?.start_at){setStartAt(new Date(payload?.startAt??value.start_at).getTime());setPhase('countdown')}})}return()=>{void removeMatchChannel(channel.current)}},[p.matchId]);
 useEffect(()=>{if(!startAt)return;const timer=setInterval(()=>{const now=Date.now();if(now<startAt){setPhase('countdown');setRemaining(Math.ceil((startAt-now)/1000));return}const left=Math.ceil((startAt+60000-now)/1000);if(left>0){setPhase('active');setRemaining(left);if(demo)setOpponentScore(Math.min(15,Math.floor((60-left)/4.2)))}else{setRemaining(0);setPhase('result');setCamera(false);if(p.matchId)void invokePvp('finalize',{matchId:p.matchId}).then(result=>{const other=result.participants?.find(item=>item.user_id!==profile.userId);if(other){setOpponentScore(other.score);setOpponentName(other.nickname)}}).catch(()=>{})}},100);return()=>clearInterval(timer)},[startAt,demo,p.matchId,profile.userId]);
 const becomeReady=useCallback(async()=>{if(phase!=='waiting')return;setHint('Ждём соперника');if(demo){setStartAt(Date.now()+3500);setPhase('countdown');return}if(!p.matchId)return;try{const result=await invokePvp('ready',{matchId:p.matchId});const match=result.match as PvpMatch|undefined;const other=match?.participants?.find(item=>item.nickname!==p.nickname);if(other)setOpponentName(other.nickname);if(match?.startAt){setStartAt(new Date(match.startAt).getTime());setPhase('countdown')}}catch{setError('Не удалось отметить готовность.')}},[phase,demo,p.matchId,p.nickname]);
 const onEvent=useCallback((event:CameraEvent)=>{if(event.type==='error'){setError(event.message??'Камера недоступна');return}if(event.type!=='pose')return;const o=event.observation,valid=!!o&&o.confidence>=.55&&Number.isFinite(o.elbowAngle)&&o.armConfidence!>=.55;if(phase==='waiting'){stable.current=valid&&o?.legsVisible?stable.current+1:0;if(stable.current>=8)void becomeReady();else setHint(!valid?'Покажи себя целиком':!o?.legsVisible?'Отойди, чтобы были видны стопы':'Не двигайся секунду');return}if(phase!=='active')return;const result=engine.current.update(valid?o!:null,Date.now());if(!valid)setHint('Вернись в кадр');else if(engine.current.counter?.needsFeet)setHint('Покажи стопы');else if(engine.current.counter?.needsBodyMovement)setHint('Опусти корпус');else setHint(engine.current.counter?.phase==='bottom'?'Вверх':'Опускайся');if(result.rep){const next=engine.current.counter!.count;setScore(next);seq.current++;void broadcastScore(channel.current,next,seq.current);if(p.matchId)void invokePvp('checkpoint',{matchId:p.matchId,score:next,sequence:seq.current}).catch(()=>{});void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light).catch(()=>{});playRepSound();Animated.sequence([Animated.timing(pulse,{toValue:1.12,duration:70,useNativeDriver:true}),Animated.timing(pulse,{toValue:1,duration:150,useNativeDriver:true})]).start()}},[phase,becomeReady,p.matchId,playRepSound,pulse]);
 const outcome=score===opponentScore?'draw':score>opponentScore?'win':'loss';
 const saveResult=async()=>recordSession({id:`pvp-${p.matchId??startAt}`,date:new Date().toISOString(),reps:score,seconds:60,goal:0,mode:'pvp',pvpResult:outcome,synced:!demo});
 const save=async()=>{if(saving)return;setSaving(true);try{await saveResult();router.replace('/(tabs)/home')}catch{setError('Не удалось сохранить результат.');setSaving(false)}};
 const rematch=async()=>{if(saving)return;setSaving(true);try{await saveResult();if(demo){router.replace({pathname:'/pvp/match',params:{demo:'1',nickname:p.nickname,opponent:opponentName}});return}if(!p.matchId)throw new Error();const result=await invokePvp('rematch',{matchId:p.matchId});const matchId=result.matchId??result.match?.id;if(!matchId)throw new Error();router.replace({pathname:'/pvp/match',params:{matchId,nickname:p.nickname,code:result.code??result.match?.code??''}})}catch{setError('Не удалось начать реванш.');setSaving(false)}};
 const addFriend=async()=>{if(!p.matchId||demo)return;try{await invokePvp('add_friend',{matchId:p.matchId});setFriendAdded(true)}catch{setError('Не удалось добавить соперника.')}};
 if(phase==='result'){const result=outcome==='draw'?'Ничья':outcome==='win'?'Победа':'Поражение';return <View style={[s.result,{paddingTop:insets.top+26,paddingBottom:insets.bottom+20}]}><StatusBar style="dark"/><Text style={s.resultKicker}>{result}</Text><View style={s.finalRow}><View><Text style={s.who}>Ты</Text><Text style={s.finalScore}>{score}</Text></View><Text style={s.dash}>—</Text><View><Text style={s.who}>{opponentName}</Text><Text style={s.finalScore}>{opponentScore}</Text></View></View>{error?<Text style={s.resultError}>{error}</Text>:null}<View style={s.actions}>{!demo?<PrimaryButton title={friendAdded?'Добавлен в друзья':'Добавить в друзья'} tone="plain" disabled={friendAdded||saving} onPress={()=>void addFriend()}/>:null}<PrimaryButton title={saving?'Сохраняем…':'Реванш'} disabled={saving} onPress={()=>void rematch()}/><PrimaryButton title={saving?'Сохраняем…':'Готово'} tone="plain" disabled={saving} onPress={()=>void save()}/></View></View>}
 return <View style={s.camera}><StatusBar hidden/>{camera?<Awake/>:null}{camera?<CameraFeed onEvent={onEvent}/>:null}<View style={[s.scoreboard,{top:insets.top+14}]}><View><Text style={s.name}>ТЫ</Text><Animated.Text style={[s.score,{transform:[{scale:pulse}]}]}>{score}</Animated.Text></View><View style={s.timer}><Text style={s.timerText}>{phase==='countdown'?remaining:phase==='waiting'?'—':clock(remaining)}</Text></View><View style={s.opponent}><Text style={s.name}>{opponentName.toUpperCase()}</Text><Text style={s.score}>{opponentScore}</Text></View></View><View style={s.center}><Text style={s.phase}>{phase==='countdown'?remaining:hint}</Text>{p.code?<Text style={s.code}>Код {p.code}</Text>:null}</View><View style={[s.bottom,{bottom:Math.max(insets.bottom,16)}]}>{error?<Text style={s.error}>{error}</Text>:null}{phase==='waiting'&&p.code?<Pressable style={s.share} onPress={()=>void Share.share({message:`Вызов в Rep: rep:///pvp?code=${p.code}`})}><Text style={s.leaveText}>Поделиться кодом</Text></Pressable>:null}<Pressable style={s.leave} onPress={()=>{if(p.matchId)void invokePvp('leave',{matchId:p.matchId});router.replace('/(tabs)/home')}}><Text style={s.leaveText}>Выйти</Text></Pressable></View></View>}
const s=StyleSheet.create({camera:{flex:1,backgroundColor:'#050505'},scoreboard:{position:'absolute',left:16,right:16,backgroundColor:'rgba(0,0,0,.62)',borderRadius:22,padding:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},name:{fontSize:10,color:'#C7C7CC',fontWeight:'700'},score:{fontSize:42,lineHeight:48,color:'#fff',fontWeight:'800'},opponent:{alignItems:'flex-end'},timer:{backgroundColor:'#fff',borderRadius:18,paddingHorizontal:14,paddingVertical:8},timerText:{fontSize:18,fontWeight:'800'},center:{position:'absolute',top:'46%',alignSelf:'center',alignItems:'center'},phase:{color:'#fff',fontSize:20,fontWeight:'700',backgroundColor:'rgba(0,0,0,.58)',paddingHorizontal:18,paddingVertical:11,borderRadius:22,overflow:'hidden'},code:{color:'#fff',marginTop:8,fontSize:12},bottom:{position:'absolute',left:20,right:20,gap:9},leave:{height:54,borderRadius:18,borderWidth:1,borderColor:'rgba(255,255,255,.65)',backgroundColor:'rgba(0,0,0,.4)',alignItems:'center',justifyContent:'center'},share:{height:48,borderRadius:18,backgroundColor:'rgba(0,0,0,.62)',alignItems:'center',justifyContent:'center'},leaveText:{color:'#fff',fontSize:16,fontWeight:'700'},error:{color:'#fff',textAlign:'center',marginBottom:8},resultError:{color:colors.red,textAlign:'center'},result:{flex:1,backgroundColor:colors.bg,paddingHorizontal:22,justifyContent:'space-between'},resultKicker:{fontSize:42,fontWeight:'800',letterSpacing:-1.5},finalRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-around'},who:{fontSize:13,color:colors.secondary,textAlign:'center',fontWeight:'700'},finalScore:{fontSize:84,fontWeight:'800',letterSpacing:-4},dash:{fontSize:34,color:colors.tertiary},actions:{gap:10}});
